global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.ayml

scrape_configs:
  - job_name: 'inventory_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory-service:8080']  # Use container name